env_args: {}
id: 0
tonic:
  after_training: None
  agent: "PPO(\n  replay=Segment(size=128)\n)\n"
  before_training: None
  checkpoint: last
  environment: 'deprl.environments.Gym(''gait_40_dof_22_musc_sagittal_vel_reward-v0'')

    '
  full_save: false
  header: 'from deprl.vendor.tonic.torch.agents.ppo import PPO

    from deprl.vendor.tonic.replays import Segment

    from ef_ppo.base_trainer import BaseTrainer

    import gait_40_dof_22_musc_sagittal

    '
  name: ppo
  parallel: 16
  resume: 1
  seed: 0
  sequential: 32
  test_environment: null
  trainer: "BaseTrainer(epoch_steps = 128 * 16 * 32, \n            save_steps = 128\
    \ * 16 * 32 * 16)\n"
working_dir: .
