DEP:
  bias_rate: 0.002
  buffer_size: 200
  intervention_length: 5
  intervention_proba: 0.0004
  kappa: 1169.7
  normalization: independent
  q_norm_selector: l2
  regularization: 32
  s4avg: 2
  sensor_delay: 1
  tau: 40
  test_episode_every: 3
  time_dist: 5
  with_learning: true
env_args: {}
id: 0
tonic:
  after_training: None
  agent: "DEP_EF_PPO(\n  replay=HLSegment(\n    size=128,\n    discount_factor=0.99,\n\
    \    trace_decay=0.9,\n    batch_size=128,\n    h_term_penalty=1.8,\n    l_term_penalty=2.7\n\
    \  ), \n  model=HLActorCritic(\n    actor=models.Actor(\n      encoder=models.ObservationEncoder(),\n\
    \      torso=models.MLP((256, 256), torch.nn.ReLU),\n      head=models.DetachedScaleGaussianPolicyHead(),\n\
    \    ),\n    l_critic=models.Critic(\n      encoder=models.ObservationEncoder(),\n\
    \      torso=models.MLP((256, 256), torch.nn.ReLU),\n      head=models.ValueHead(),\n\
    \    ), \n    h_critic=models.Critic(\n      encoder=models.ObservationEncoder(),\n\
    \      torso=models.MLP((256, 256), torch.nn.ReLU),\n      head=models.ValueHead(),\n\
    \    ), \n    observation_normalizer=normalizers.MeanStd(), \n  ), \n  actor_updater=updaters.actors.ClippedRatio(\n\
    \    optimizer=lambda params: torch.optim.Adam(params, lr=3e-5),\n    entropy_coeff=0.001,\n\
    \    ratio_clip=0.20 \n  ), \n  h_critic_updater=VRegression(\n    optimizer=lambda\
    \ params: torch.optim.Adam(params, lr=4e-5),\n  ),\n  l_critic_updater=VRegression(\n\
    \    optimizer=lambda params: torch.optim.Adam(params, lr=4e-5),\n  ),\n  max_budget=2.7\n\
    )\n"
  before_training: None
  checkpoint: last
  environment: "deprl.environments.Gym('gait_40_dof_22_musc_sagittal_neg_reward-v0',\n\
    \                       scaled_actions=False, \n                       reset_type='random')\n"
  full_save: 0
  header: 'import torch

    global torch

    from ef_ppo.ef_ppo import DEP_EF_PPO

    from ef_ppo.hl_segment import HLSegment

    from ef_ppo.models import HLActorCritic

    from ef_ppo.hl_segment import HLSegment

    from ef_ppo.critics import VRegression

    from deprl.vendor.tonic.torch import models, normalizers, updaters

    import ef_ppo, deprl, gym, myosuite, gait_40_dof_22_musc_sagittal

    '
  name: ef_ppo_refractor
  parallel: 16
  resume: 1
  seed: 0
  sequential: 32
  test_environment: null
  trainer: "ef_ppo.base_trainer.EFPPOTrainer(\n  steps=int(1e8),\n  epoch_steps=int(128\
    \ * 16 * 32 * 8),\n  save_steps=int(128 * 16 * 32 * 8),\n  test_episodes=10,\n\
    \  discount=0.99,\n  constraint_function=\"lambda observations, muscle_states:\
    \ \"\n                      \"np.abs(observations[:, 39].flatten() * 100 - 1.2)\
    \ - 0.1\",\n  max_budget=2.7\n)\n"
working_dir: .
